version: '3.8'
services:
  database:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: event_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: local_admin
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
  api1:
    image: API2
    build:
      context: .
    ports:
      - "8000:80"
volumes:
  db_data: