name: deploy

inputs:
  API_NAME: 
    required: true
  DOCKER_USERNAME: 
    required: true
  DOCKER_PASSWORD:
    required: true
  DOCKER_REPOSITORY:
    required: true
  DOCKERFILE_PATH:
    required: true

runs:
  using: "composite"
  steps:
  - name: Docker login
    env:
      DOCKER_USERNAME: ${{ inputs.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ inputs.DOCKER_PASSWORD }}
    run: |
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    shell: bash

  - name: Build the Docker image
    run: |
      docker build -t ${{ inputs.API_NAME }} -f Dockerfile .
    shell: bash

  - name: Tag the Docker image
    run: |
      docker tag ${{ inputs.API_NAME }} ${{ inputs.DOCKER_REPOSITORY }}:${{ inputs.API_NAME }}
    shell: bash

  - name: Push the Docker image
    run: |
      docker push ${{ inputs.DOCKER_REPOSITORY }}:${{ inputs.API_NAME }}
    shell: bash