name: deploy

inputs:
  API_NAME: 
    required: true

runs:
  using: "composite"
  steps:
  - name: Checkout the files
    uses: actions/checkout@v3

  - name: Docker login
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    run: |
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

  - name: Build the Docker image
    run: |
      docker build -t ${{ inputs.API_NAME }} -f Dockerfile .

  - name: Tag the Docker image
    run: |
      docker tag ${{ inputs.API_NAME }} ${{ inputs.API_NAME }}:latest

  - name: Push the Docker image
    run: |
      docker push ${{ inputs.API_NAME }}:latest